name: untitled
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/wooden fish.png
    - assets/waw/da.wav
    - assets/waw/dong.mp3
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico.ttf
